config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root "products#index"
  mount TaiwanCity::Engine => '/taiwan_city'

  namespace :admin do
    resources :products do
      resources :photos, only: [:create, :destroy]
    end
    resources :orders do
      member do
        post :cancel
        post :ship
        post :shipped
        post :return
      end
    end
    resources :users do
      member do
        post :to_admin
        post :to_normal
      end
    end
    resources :product_options, only: :index
    resources :purchases
    resources :sales
    resources :sale_platforms
    resources :inventories do
      resources :inventory_transactions
    end
  end

  namespace :account do
    resources :orders
  end


  resources :orders do
    member do
      get :pay_with_credit_card
      post :pay2go_cc_notify
    end
  end
  resources :carts do
    collection do
      post :checkout
      delete :clean
    end
  end
  resources :products do
    member do
      post :add_to_cart
    end
  end
  resources :inventories, only: :index
  resources :items, controller: "cart_items"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/order.rb
class Order < ApplicationRecord
  include AASM
  include Tokenable
  belongs_to :user
  has_many :items, class_name: "OrderItem", dependent: :destroy
  has_one :info, class_name: "OrderInfo", dependent: :destroy


  accepts_nested_attributes_for :info

  def build_item_cache_from_cart(cart)
    cart.cart_items.each do |cart_item|
      item = items.build
      item.product_name = cart_item.product.title
      item.color_name = cart_item.color.name
      item.dimension_name = cart_item.dimension.name
      item.quantity = cart_item.quantity
      item.price = cart_item.product.price
      item.save
    end
  end

  def calculate_total!(cart)
    self.total = cart.total_price
    self.save
  end


  def set_payment_with!(method)
    self.update_columns(payment_method: method)
  end

  def pay!
    self.update_columns(is_paid: true)
  end

  aasm do
    state :order_placed, initial: true
    state :paid
    state :shipping
    state :shipped
    state :order_cancelled
    state :good_returned

    event :make_payment , after_commit: :pay! do
      transitions from: :order_placed, to: :paid
    end

    event :ship do
      transitions from: :paid, to: :shipping
    end

    event :deliver do
      transitions from: :shipping, to: :shipped
    end

    event :return_good do
      transitions from: :shipped, to: :good_returned
    end

    event :cancell_order do
      transitions from: [:order_placed, :paid], to: :order_cancelled
    end




  end

end

app/controllers/account/orders_controller.rb
class Account::OrdersController < ApplicationController
  before_action :authenticate_user!

  def index
    @orders = current_user.orders.order("id DESC")
  end

end

app/controllers/admin/orders_controller.rb
class Admin::OrdersController < AdminController

  before_action :find_order, only: [:ship,:shipped,:cancel,:return]

  def index
    @orders = Order.order("id DESC")
  end

  def show
    @order = Order.find(params[:id])
    @order_info = @order.info
    @order_items = @order.items
  end

  def ship
    @order.ship!
    redirect_to :back
  end

  def shipped
    @order.deliver!
    redirect_to :back
  end

  def cancel
    @order.cancell_order!
    redirect_to :back
  end

  def return
    @order.return_good!
    redirect_to :back
  end

  private
  def find_order
    @order = Order.find(params[:id])
  end

end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  before_action :authenticate_user!, except: :pay2go_cc_notify
  protect_from_forgery except: :pay2go_cc_notify

  def create
    @order = current_user.orders.build(order_params)

    if @order.save
      OrderPlaceingService.new(current_cart, @order).place_order!
      redirect_to order_path(@order.token)
    else
      render "carts/checkout"
    end
  end


  def show
    @order = Order.find_by_token(params[:id])
    @order_info = @order.info
    @order_items = @order.items
  end

  def pay_with_credit_card
    @order = Order.find_by_token(params[:id])
    @order.set_payment_with!("credit_card")
    @order.make_payment!

    redirect_to account_orders_path, notice: "成功完成付款"
  end

  def pay2go_cc_notify
    @order = Order.find_by_token(params[:id])

    if params["Status"] == "SUCCESS"
      @order.make_payment!
      if @order.is_paid?
        flash[:notice] = "信用卡付款成功"
        redirect_to account_orders_path
      else
        render text: "信用卡失敗"
      end
    else
      render text: "交易失敗"
    end
  end


  private
  def order_params
    params.require(:order).permit(info_attributes:[:billing_name,
                                                   :billing_address,
                                                   :shipping_name,
                                                   :shipping_address])
  end
end

app/helpers/account/orders_helper.rb
module Account::OrdersHelper
end

app/helpers/admin/orders_helper.rb
module Admin::OrdersHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
  def render_order_state(order)
    t("orders.order_state.#{order.aasm_state}")
  end

  def render_order_paid_state(order)
    if order.is_paid?
      "已付款"
    else
      "未付款"
    end
  end
end

app/views/admin/orders/_state_option.html.erb
<div style="padding:10px; float:right;">
  <% case order.aasm_state %>
  <% when "order_placed" %>
    <%= link_to("取消訂單",cancel_admin_order_path(order),class:"btn btn-default btn-sm",method: :post) %>
  <% when "paid" %>
    <%= link_to("取消訂單",cancel_admin_order_path(order),class:"btn btn-default btn-sm",method: :post) %>
    <%= link_to("出貨", ship_admin_order_path(order),method: :post, class:"btn btn-default btn-sm") %>
  <% when "shipping" %>
    <%= link_to("設為已出貨", shipped_admin_order_path(order),method: :post, class:"btn btn-default btn-sm") %>
  <% when "shipped" %>
    <%= link_to("退貨",return_admin_order_path(order),method: :post, class: "btn btn-default btn-sm") %>
  <% when "order_cancelled" %>
    <span class="label label-default">訂單已取消</span>
  <% when "good_returned" %>
    <span class="label label-default">已退貨</span>
  <% end %>
</div>

app/views/admin/orders/index.html.erb
<div class="wrapper wrapper-content animated fadeInRight ecommerce">
  <div class="row">
    <div class="col-lg-12">
      <div class="ibox">
        <div class="ibox-title">
          <h2>訂單列表</h2>
        </div>
        <div class="ibox-content">
          <table class="table table-bordered">
            <thead>
              <tr>
                <th>#</th>
                <th>生成時間</th>
                <th>訂購者</th>
                <th>訂單狀態</th>
              </tr>
            </thead>
            <tbody>
              <% @orders.each do |order| %>
                <tr>
                  <td><%= link_to(order.id,admin_order_path(order)) %></td>
                  <td><%= order.created_at.to_s(:long) %></td>
                  <td><%= order.user.email %></td>
                  <td><%= render_order_state(order) %></td>
                </tr>
              <% end %>
            </tbody>
          </table>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/admin/orders/show.html.erb
<div class="wrapper wrapper-content animated fadeInRight ecommerce">
  <div class="row">
    <div class="col-lg-12">
      <div class="ibox">
        <div class="ibox-title">
          <h2>訂單明細 <%= render_order_paid_state(@order) %></h2>
        </div>
        <div class="ibox-content">
          <%= render "admin/orders/state_option", order:@order %>
          <table class="table table-bordered">
            <thead>
              <tr>
                <th width="80%">商品明細</th>
                <th>單價</th>
                <th>數量</th>
              </tr>
            </thead>
            <tbody>
              <% @order_items.each do |order_item|%>
                <tr>
                  <td><%= order_item.product_name %></td>
                  <td><%= order_item.price %></td>
                  <td><%= order_item.quantity %></td>
                </tr>
              <% end %>
            </tbody>
          </table>
          <div class="total clearfix">
            <span class="pull-right">
              <span>總計 <%= @order.total %></span>
            </span>
          </div>
          <hr>
          <h2>寄送資訊</h2>
          <table class="table table-striped table-bordered">
            <tbody>
              <tr>
                <td>訂購人</td>
              </tr>
              <tr>
                <td><%= @order_info.billing_name %> - <%= @order_info.billing_address %></td>
              </tr>
              <tr>
                <td>收件人</td>
              </tr>
              <tr>
                <td><%= @order_info.shipping_name %> - <%= @order_info.shipping_address %></td>
              </tr>
            </tbody>
          </table>
        </div>
      </div>
    </div>