config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root "products#index"
  mount TaiwanCity::Engine => '/taiwan_city'

  namespace :admin do
    resources :products do
      resources :photos, only: [:create, :destroy]
    end
    resources :orders do
      member do
        post :cancel
        post :ship
        post :shipped
        post :return
      end
    end
    resources :users do
      member do
        post :to_admin
        post :to_normal
      end
    end
    resources :product_options, only: :index
    resources :purchases
    resources :sales
    resources :sale_platforms
    resources :inventories do
      resources :inventory_transactions
    end
  end

  namespace :account do
    resources :orders
  end


  resources :orders do
    member do
      get :pay_with_credit_card
      post :pay2go_cc_notify
    end
  end
  resources :carts do
    collection do
      post :checkout
      delete :clean
    end
  end
  resources :products do
    member do
      post :add_to_cart
    end
  end
  resources :inventories, only: :index
  resources :items, controller: "cart_items"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/cart.rb
class Cart < ApplicationRecord
  has_many :cart_items, dependent: :destroy
  has_many :items, through: :cart_items, source: :product


  def add_product_to_cart(product, color, dimension, quantity)
    ci = cart_items.build
    ci.product = product
    ci.color_id = color
    ci.dimension_id = dimension
    ci.quantity = quantity
    ci.save
  end

  def total_price
    sum = 0
    cart_items.each do |cart_item|
      sum = sum + (cart_item.product.price * cart_item.quantity)
    end
    sum
  end

  def clean!
    cart_items.destroy_all
  end

  def find_cart_item(product)
    cart_items.find_by(product_id: product)
  end

end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  before_action :authenticate_user!, only: [:checkout]

  def checkout
    @order = current_user.orders.build
    @info = @order.build_info
  end

  def clean
    current_cart.clean!
    flash[:warning] = "已清空購物車"
    redirect_to carts_path
  end



end

app/helpers/carts_helper.rb
module CartsHelper
  def render_cart_total_price(cart)
    cart.total_price
  end

  def render_cart_item_sub_total(cart_item)
    cart_item.product.price * cart_item.quantity
  end
end

app/views/carts/checkout.html.erb
<div class="wrapper wrapper-content animated fadeInRight ecommerce">
  <div class="row">
    <div class="col-md-12">
      <div class="ibox">
        <div class="ibox-title">
          <h2>購物明細</h2>
        </div>
        <div class="ibox-content">
          <table class="table table-bordered">
            <thead>
              <tr>
                <th width="70%">商品明細</th>
                <th>顏色</th>
                <th>尺吋</th>
                <th>單價</th>
                <th>數量</th>
                <th>小計</th>
              </tr>
            </thead>
            <tbody>
              <% current_cart.cart_items.each do  |cart_item|%>
                <tr>
                  <td>
                    <%= link_to(cart_item.product.title, product_path(cart_item.product)) %>
                  </td>
                  <td><%= cart_item.color.name %></td>
                  <td><%= cart_item.dimension.name %></td>
                  <td>
                    <%= cart_item.product.price %>
                  </td>
                  <td><%= cart_item.quantity %></td>
                  <td><%= render_cart_item_sub_total(cart_item) %></td>
                </tr>
              <% end %>
            </tbody>
          </table>
          <div class="total clearfix">
            <span class="pull-right">
              總計 <%= render_cart_total_price(current_cart) %> NTD
            </span>
          </div>
        </div>
      </div>
    </div>
  </div>
  <div class="row">
    <div class="col-md-12">
      <div class="ibox">
        <div class="ibox-title">
          <h2>訂單資訊</h2>
        </div>
        <div class="ibox-content">
          <div class="row">
            <%= simple_form_for @order do |f| %>
              <%= f.simple_fields_for :info do |c| %>
                <legend>訂購人</legend>
                <div class="for-group col-lg-6">
                  <%= c.input :billing_name %>
                </div>
                <div class="for-group col-lg-6">
                  <%= c.input :billing_address %>
                </div>
                <legend>收貨人</legend>
                <div class="for-group col-lg-6">
                  <%= c.input :shipping_name %>
                </div>
                <div class="for-group col-lg-6">
                  <%= c.input :shipping_address %>
                </div>
              <% end %>
            </div>
            <div class="row">
              <div class="checkout">
                <%= f.submit "生成訂單", class: "btn btn-lg btn-danger pull-right", data:{disable_with: "Submitting..."} %>
              </div>
            </div>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/carts/index.html.erb
<div class="wrapper wrapper-content animated fadeInRight ecommerce">
  <div class="row">
    <div class="col-md-12">
      <div class="ibox">
        <div class="ibox-title">
          <h2>購物車</h2>
        </div>
        <div class="ibox-content">
          <%= link_to("清空購物車", clean_carts_path, method: :delete, class:"pull-right",style:"text-decoration:underline;",data:{confirm:"你確定要清空整個購物車嗎？"}) %>
          <br>
          <br>
          <table class="table table-bordered">
            <thead>
              <tr>
                <th colspan="2">商品資訊</th>
                <th>顏色</th>
                <th>尺吋</th>
                <th>數量</th>
                <th>單價</th>
                <th>操作選項</th>
              </tr>
            </thead>
            <tbody>
              <% current_cart.cart_items.each do |cart_item| %>
                <tr>
                  <td>
                    <% if cart_item.product.photo.present? %>
                      <%= image_tag(cart_item.product.photo.images.first.thumb.url,class:"thumbnail") %>
                    <% else %>
                      <%= image_tag("http://placehold.it/50x50&No Pic", class: "thumbnail") %>
                    <% end %>
                  </div>
                </td>
                <td>
                  <%= link_to(cart_item.product.title,product_path(cart_item.product)) %>
                </td>

                <%= simple_form_for cart_item, url: item_path(cart_item) do |f| %>
                  <td data-pid="<%= cart_item.product.id  %>"> <%= f.association :color,as: :select, collection: Inventory.getColorOption(f.object.product_id),label_method: :text, input_html: { class:"select_color" }, label: false,include_blank: false, include_hidden: false  %></td>
                  <td data-pid="<%= cart_item.product.id  %>"><%= f.association :dimension, as: :select, collection: Inventory.getDimensionOption(f.object.product_id, f.object.color_id),label_method: :text, input_html: { class:"select_dimension" }, label: false, include_blank: false, include_hidden: false  %></td>
                  <td>
                    <%= f.input :quantity, input_html: { class:"select_quantity" , max: Inventory.getInventory(f.object.product, f.object.color_id, f.object.dimension_id).first.quantity, min: 0}, label: false %>
                  </td>

                  <td><%= cart_item.product.price %></td>
                  <td >
                    <%= f.submit "更新", data: {disable_with: "Submiting..."}, class: "btn btn-primary btn-outline" %>
                  <% end %>
                  <%= link_to item_path(cart_item), method: :delete , class: "btn btn-danger btn-outline" do  %>
                    <i class="fa fa-trash"></i>
                  <% end %>
                </td>

              </tr>
            <% end %>
          </tbody>
        </table>
        <br>
        <div class="total clearfix">
          <span class="pull-right">
            <span>
              總計 <%= render_cart_total_price(current_cart) %> NTD
        </span>
          </span>
        </div>
        <hr>
        <div class="checkout clearfix">
          <%= link_to("確認結帳", checkout_carts_path , method: :post, class: "btn btn-lg btn-danger pull-right") %>
        </div>
      </div>
    </div>
  </div>
</div>
</div>
<script type="text/javascript">
  $(function() {
      var select2BaseConfig, select2ColorConfig, select2DimensionConfig, select2QuantityConfig;
      select2BaseConfig= {
        theme: "bootstrap",
        escapeMarkup: function(markup) {
          return markup;
        },
        placeholder: {
          id: '-1',
          text: 'Select an Option'
        },
        width: '100%'
      };
      select2ColorConfig = select2DimensionConfig = select2QuantityConfig = select2BaseConfig;
      $('.select_color, .select_dimension').select2(select2BaseConfig);

      $('.select_color').on('select2:select', function(e) {
        var color_id = $(this).val(),
          $select_product = $(this).parent().parent().data("pid"),
          $selct_dimension = $(this).parent().parent().next().find(".select_dimension");

          url = "/admin/inventories.json";
        $.ajax({
          url: url,
          dataType: "JSON",
          data: {
            getDimensionOption: [$select_product, color_id]
          },
          success: function(data) {
            $selct_dimension.prop("disabled", false);
            removeOption($selct_dimension);
            select2DimensionConfig.data = data;
            select2DimensionConfig.placeholder.text = 'Select Dimension'
            $selct_dimension.select2(select2DimensionConfig).select2('val', -1);
          }
        });
      });

      $('.select_dimension').on('select2:select', function(e) {
        var dimension_id = $(this).val(),
          $parentTD = $(this).parent().parent(),
          $select_product = $parentTD.data("pid"),
          $select_color = $parentTD.prev().find(".select_color"),
          $select_quantity = $parentTD.next().find(".select_quantity");
          url = "/admin/inventories.json";
        $.ajax({
          url: url,
          dataType: "JSON",
          data: {
            getInventory: [$select_product, $select_color.val(), dimension_id ]
          },
          success: function(data) {
            $select_quantity.prop("disabled", false);
            $select_quantity.val(0);
            $select_quantity.attr("max",data[0].quantity);
          }
        });
      });

  });
</script>