config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root "products#index"
  mount TaiwanCity::Engine => '/taiwan_city'

  namespace :admin do
    resources :products do
      resources :photos, only: [:create, :destroy]
    end
    resources :orders do
      member do
        post :cancel
        post :ship
        post :shipped
        post :return
      end
    end
    resources :users do
      member do
        post :to_admin
        post :to_normal
      end
    end
    resources :product_options, only: :index
    resources :purchases
    resources :sales
    resources :sale_platforms
    resources :inventories do
      resources :inventory_transactions
    end
  end

  namespace :account do
    resources :orders
  end


  resources :orders do
    member do
      get :pay_with_credit_card
      post :pay2go_cc_notify
    end
  end
  resources :carts do
    collection do
      post :checkout
      delete :clean
    end
  end
  resources :products do
    member do
      post :add_to_cart
    end
  end
  resources :inventories, only: :index
  resources :items, controller: "cart_items"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/product.rb
class Product < ApplicationRecord
  include Filterable
  validates :title,:price ,presence: true
  has_one :photo, dependent: :destroy
  has_many :product_options, dependent: :destroy
  has_many :dimensions, :through => :product_options, source: :dimension
  has_many :colors, :through => :product_options, source: :color
  has_many :inventories

  accepts_nested_attributes_for :photo, :allow_destroy => true
  accepts_nested_attributes_for :product_options, :allow_destroy => true,:reject_if => :all_blank
  accepts_nested_attributes_for :dimensions, :allow_destroy => true
  accepts_nested_attributes_for :colors, :allow_destroy => true

  scope :q_name,  -> (name) { where "title like ?", "%#{name}%"}
  scope :get_inventory,-> (qty) {
    joins(:inventories)
    .select("products.id, products.title")
    .where("inventories.quantity > ?",qty).group("products.id")
  }
  scope :q_name_with_inven, -> (name) {
    joins(:inventories)
    .select("products.id, products.title")
    .where("title like ? and inventories.quantity > 0","%#{name}%").group("products.id")
  }
end

app/controllers/admin/products_controller.rb
class Admin::ProductsController < AdminController

  def new
    @product = Product.new
    @photo = @product.build_photo
  end

  def create
    @product = Product.new(product_params)
    if @product.save
      redirect_to admin_products_path
    else
      puts "-----------------"
      puts "#{@product.errors.messages}"
      render :new
    end
  end

  def index
    @products = Product.filter(params.slice(:q_name,:q_name_with_inven,:get_inventory))
    respond_to do |format|
      format.html
      format.json do
        render json: @products
      end
    end
  end

  def edit
    @product = Product.find(params[:id])
    if @product.photo.present?
      @photo = @product.photo
    else
      @photo = @product.build_photo
    end
  end

  def update
    @product = Product.find(params[:id])
    if @product.update(product_params)
      redirect_to admin_products_path
    else
      render :edit
    end

  end

  def destroy
    @product = Product.find(params[:id])
    @product.destroy
    redirect_to admin_products_path
  end

  private
  def product_params
    if params.dig(:product,:photo_attributes,:images)
      params[:product][:photo_attributes][:images] = params[:product][:photo_attributes][:images].values
    end
    params.require(:product).permit(:title,:description,:quantity,:price,
                                    photo_attributes:[:id,{ images:[] }],
                                    product_options_attributes:[:id,:color_id,:dimension_id,:_destroy,
                                                                dimension_attributes:[:id,:name,:_destroy],
                                                                color_attributes:[:id,:name,:_destroy]]
                                    )
  end

end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  def index
    @products = Product.all
  end

  def show
    @product = Product.find(params[:id])
  end

  def add_to_cart
    @product = Product.find(params[:id])
    if (!params[:cart].blank? && !params[:cart][:cart_items].blank? && !params[:cart][:cart_items][:color_id].blank? && !params[:cart][:cart_items][:dimension_id].blank?)
      @color = params[:cart][:cart_items][:color_id]
      @dimension = params[:cart][:cart_items][:dimension_id]
      @quantity = params[:cart][:cart_items][:quantity] || 1
      current_cart.add_product_to_cart(@product,@color,@dimension,@quantity)
      flash[:notice] = "你已成功將#{@product.title} 加入購物車"
    else
      flash[:warning] = "請選擇顏色或尺吋"
    end

    redirect_to :back
  end



end

app/helpers/admin/products_helper.rb
module Admin::ProductsHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/admin/products/_color_fields.html.erb
<%= f.input :name, :hint => "It's for new color" %>

app/views/admin/products/_dimension_fields.html.erb
<%= f.input :name, :hint => "It's for new dimension" %>

app/views/admin/products/_form.html.erb
<%= simple_form_for [:admin, @product]  do |f| %>
  <div class="tabs-container">
    <ul class="nav nav-tabs">
      <li class="active"><a data-toggle="tab" href="#tab-1"> Product info</a></li>
      <li class=""><a data-toggle="tab" href="#tab-2"> Options</a></li>
      <li class=""><a data-toggle="tab" href="#tab-3"> Images</a></li>
    </ul>
    <div class="tab-content">
      <div id="tab-1" class="tab-pane active">
        <div class="panel-body">
          <div class="group">
            <%= f.input :title %>
          </div>
          <div class="group">
            <%= f.input :description, :input_html => { 'rows' => 5} %>
          </div>
          <div class="group">
            <%= f.input :price %>
          </div>
        </div>
      </div>
      <div id="tab-2" class="tab-pane">
        <div class="panel-body">
          <label>Options</label>
          <div class="row-fluid">
            <div class="col-md-offset-1">
              <div id="options">
                <div class="row-fluid">
                  <%= link_to_add_association 'new option', f, :product_options,
          'data-association-insertion-method' => 'append',
          'data-association-insertion-node' => 'table',
          class: "btn btn-danger pull-right" %>
                  <br>
                  <table class="table">
                    <tbody>
                      <%= f.simple_fields_for :product_options do |product_option| %>
                        <%= render 'product_option_fields', :f => product_option %>
                      <% end %>
                    </tbody>
                  </table>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
      <div id="tab-3" class="tab-pane">
        <div class="panel-body">
          <div id="myDropzone" class="dropzone">
            <%= f.simple_fields_for :photo do |c| %>
              <div class="fallback">
                <%= c.input :images , as: :file, input_html: { multiple: 'multiple'} %>
              </div>
            <% end %>
          </div>
        </div>
      </div>
    </div>
    <br>
    <%= f.submit "Submit", class:"btn btn-info pull-right",data:{disable_with: "Submitting..."} %>
  </div>
<% end %>

app/views/admin/products/_product_fields.html.erb
<tr>
  <td><%= product.id %></td>
  <td>
    <%= product.title %>
  </td>
  <td class="align-text-top">
    <%= link_to product_path(product) do %>
      <div class="row">
        <%= render :partial => "common/product_images" , locals:{ product: product, image_type: "thumb" }%>
      </div>
    <% end %>
  </td>
  <td>
    <%= simple_format(product.description) %>
  </td>
  <td>
    <%= product.price %>
  </td>
  <td class="text-right">
    <%= link_to edit_admin_product_path(product), class:"btn btn-xs btn-outline btn-primary" do %>
      <i class="fa fa-pencil-square-o">Edit</i>
    <% end %>
    <%= link_to admin_product_path(product),class:"btn btn-xs btn-outline btn-danger",method: :delete, data:{confirm:"Are you sure?"} do  %>
      <i class="fa fa-trash">Delete</i>
    <% end %>
  </td>
</tr>

app/views/admin/products/_product_option_fields.html.erb
<tr class="nested-fields">
  <td>
    <%= f.association :color, :collection => Color.all %>
    <div class="colors">
      <%= link_to_add_association 'Add new color', f, :color %>
    </div>
  </td>
  <td>
    <%= f.association :dimension, :collection => Dimension.all %>
    <div>
      <%= link_to_add_association 'Add new dimension', f, :dimension %>
    </div>
  </td>
  <td>
    <%= link_to_remove_association f, class:"btn" do %>
      <i class="fa fa-trash"></i>
    <% end %>
  </td>
</tr>

app/views/admin/products/_size_fields.html.erb
<div class="nested-fields">
  <%= link_to_remove_association  f, class:"btn btn-xs btn-danger pull-right"  do %>
    <i class="fa fa-trash"></i> Delete Size
  <% end %>
  <%= f.input :name %>
</div>

app/views/admin/products/edit.html.erb
<div class="wrapper wrapper-content ecommerce">
  <div class="row">
    <div class="col-lg-12">
      <h2>修改產品</h2>
      <%= render "form" %>
    </div>
  </div>
</div>
<script type="text/javascript">
  $(function(){
    var post_url = "/admin/products/"+<%= @product.id %>+"/photos";
    var myDropzone = new Dropzone("#myDropzone", {
      url: post_url,
      method: "POST",
      paramName: "photo[images]",
      uploadMultiple: true,
      autoProcessQueue: false,
      addRemoveLinks: true,
      parallelUploads: 100,
      maxFiles: 100,
      removedfile: function(file){
        var _ref,
            product_id = file.product_id,
            image_index = file.index,
            url = "/admin/products/" + product_id + "/photos/" + image_index;
        $.ajax({
            type: 'DELETE',
            url: url
        });
        return (_ref = file.previewElement) != null ? _ref.parentNode.removeChild(file.previewElement) : void 0;
      },
      headers: {
      'X-CSRF-Token': $('meta[name="csrf-token"]').attr('content')},
      init: function() {
        var myDropzone = this;
        $("input[type='submit']").on("click", function(e) {
            if (myDropzone.getQueuedFiles().length > 0) {
                e.preventDefault();
                e.stopPropagation();
                myDropzone.processQueue();
                return;
            }
        });
        this.on("successmultiple", function(files, response) {
          $('form').submit();
        });
      }
    });
    <% if @product.photo.images.present? %>
         <% @product.photo.images.each_with_index do |image, index| %>
            var mockFile = {
              name: "<%= image.file.filename %>",
              size: <%= image.size %>,
              index: <%= index %>,
              product_id : <%= @product.id %>
            };
            myDropzone.emit("addedfile", mockFile);
            myDropzone.createThumbnailFromUrl(mockFile, "<%= image.url %>",null, "anonymous");
            myDropzone.emit("complete", mockFile);
            myDropzone.files.push(mockFile);
        <% end %>
    <% end %>
  });
</script>

app/views/admin/products/index.html.erb
<div class="wrapper wrapper-content animated fadeInRight ecommerce">
  <div class="row">
    <div class="col-lg-12">
      <div class="ibox">
        <div class="ibox-content">
          <h2>Product List</h2>
          <div class="pull-right" style="padding-bottom:20px;">
            <%= link_to("新增產品", new_admin_product_path, class: "btn btn-primary btn-sm") %>
          </div>
          <table class="footable table table-stripped toggle-arrow-tiny" data-page-size="15">
            <thead>
              <tr>
                <th data-toggle="true">#</th>
                <th>Product Name</th>
                <th data-hide="all"></th>
                <th data-hide="all">Description</th>
                <th>Price</th>
                <th class="text-right" data-sort-ignore="true">Action</th>
              </tr>
            </thead>
            <tbody>
              <%= render :partial => "product_fields", :collection => @products, :as => :product  %>
            </tbody>
            <tfoot>
              <tr>
                <td colspan="6">
                  <ul class="pagination pull-right"></ul>
                </td>
              </tr>
            </tfoot>
          </table>
        </div>
      </div>
    </div>
  </div>
</div>
<% content_for :javascript do %>
  <script type="text/javascript">
    $(function() {
          $('.footable').footable();
        });
  </script>
<% end %>

app/views/admin/products/new.html.erb
<div class="wrapper wrapper-content ecommerce">
  <div class="row">
    <div class="col-lg-12">
      <h2>新增產品</h2>
      <%= render "form" %>
    </div>
  </div>
</div>
<script type="text/javascript">
  $(function(){
      var myDropzone = new Dropzone("#myDropzone", {
        url: "/admin/products",
        paramName: "product[photo_attributes][images]",
        uploadMultiple: true,
        addRemoveLinks: true,
        autoProcessQueue: false,
        parallelUploads: 100,
        maxFiles: 100,
        headers: {
          'X-CSRF-Token': $('meta[name="csrf-token"]').attr('content')
        },
        init: function() {
          var myDropzone = this;
          $("input[type='submit']").on("click", function(e) {
              if (myDropzone.getQueuedFiles().length > 0){
                e.preventDefault();
                e.stopPropagation();
                myDropzone.processQueue();
                return;
              }
          });
          this.on("sendingmultiple", function(data, xhr, formData) {
            $("form input, form select").each(function(){
              formData.append($(this).attr("name"), $(this).val());
            });
          });
          this.on("successmultiple", function(files, response) {
             window.location.href = '<%= admin_products_path %>'
          });
        }
      });

    });
</script>