config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root "products#index"
  mount TaiwanCity::Engine => '/taiwan_city'

  namespace :admin do
    resources :products do
      resources :photos, only: [:create, :destroy]
    end
    resources :orders do
      member do
        post :cancel
        post :ship
        post :shipped
        post :return
      end
    end
    resources :users do
      member do
        post :to_admin
        post :to_normal
      end
    end
    resources :product_options, only: :index
    resources :purchases
    resources :sales
    resources :sale_platforms
    resources :inventories do
      resources :inventory_transactions
    end
  end

  namespace :account do
    resources :orders
  end


  resources :orders do
    member do
      get :pay_with_credit_card
      post :pay2go_cc_notify
    end
  end
  resources :carts do
    collection do
      post :checkout
      delete :clean
    end
  end
  resources :products do
    member do
      post :add_to_cart
    end
  end
  resources :inventories, only: :index
  resources :items, controller: "cart_items"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/layouts/_navigation.html.erb
<nav class="navbar-default navbar-static-side" role="navigation">
    <div class="sidebar-collapse">
        <ul class="nav metismenu" id="side-menu">
            <li class="nav-header">
                <div class="dropdown profile-element">
                    <a data-toggle="dropdown" class="dropdown-toggle" href="#">
                        <span class="clear">
                            <span class="block m-t-xs">
                                <strong class="font-bold"><%= current_user.email %></strong>
                                 <b class="caret"></b>
                            </span>
                        </span>
                    </a>
                    <ul class="dropdown-menu animated fadeInRight m-t-xs">
                        <li><%= link_to("返回前台", products_path) %></li>
                        <li><%= link_to("我的訂單",account_orders_path) %></li>
                        <li class="divider"></li>
                        <li>
                        <%= link_to("登出",destroy_user_session_path, method: :delete) %>
                        </li>
                    </ul>
                </div>
                <div class="logo-element">
                    IN+
                </div>
            </li>
            <li class="<%= is_active_controller('admin/products') %>">
                <%= link_to admin_products_path do %>
                <i class="fa fa-database"></i> <span class="nav-label" data-i18n="nav.gridoptions">Products</span>
                <% end %>
            </li>
            <li class="<%= is_active_controller('admin/orders') %>">
                <%= link_to admin_orders_path do %>
                <i class="fa fa-clone"></i> <span class="nav-label" data-i18n="nav.gridoptions">Orders</span>
                <% end %>
            </li>
            <li class="<%= is_active_controller('admin/users') %>">
                <%= link_to admin_users_path do %>
                <i class="fa fa-user-circle"></i> <span class="nav-label" data-i18n="nav.gridoptions">Users</span>
                <% end %>
            </li>
            <li class="<%= is_active_controller('admin/purchases') %>">
                <%= link_to admin_purchases_path do %>
                <i class="fa fa-exchange"></i> <span class="nav-label" data-i18n="nav.gridoptions">Purchases</span>
                <% end %>
            </li>
            <li class="<%= is_active_controller('admin/sales') %>">
                <%= link_to admin_sales_path do %>
                <i class="fa fa-exchange"></i> <span class="nav-label" data-i18n="nav.gridoptions">Sales</span>
                <% end %>
            </li>
            <li class="<%= is_active_controller('admin/inventories') %>">
                <%= link_to admin_inventories_path do %>
                <i class="fa fa-cube"></i> <span class="nav-label" data-i18n="nav.gridoptions">Inventory</span>
                <% end %>
            </li>
            <li class="<%= is_active_controller('admin/sale_platforms') %>">
                <%= link_to admin_sale_platforms_path do %>
                <i class="fa fa-cubes"></i> <span class="nav-label" data-i18n="nav.gridoptions">SalePlatform</span>
                <% end %>
            </li>

        </ul>

    </div>
</nav>

app/views/layouts/admin.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MaskStore 後台</title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag params[:controller] if ::Rails.application.assets_manifest.find_sources("#{params[:controller]}.css") %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => 'reload' %>
    <meta name="turbolinks-cache-control" content="no-preview">
    <% if content_for?(:head) %>
      <%= yield(:head) %>
    <% end %>
  </head>
  <body>
    <%= Gon::Base.render_data %>
    <div id="wrapper" class="<%= params[:controller] %>.<%= params[:action] %>">
      <!-- Navigation -->
      <%= render 'layouts/navigation' %>
      <!-- Page wraper -->
      <div id="page-wrapper" class="gray-bg">
        <!-- Main view  -->
        <%= notice_message %>
        <%= yield %>
      </div>
    </div>
    <%= javascript_include_tag params[:controller] if ::Rails.application.assets_manifest.find_sources("#{params[:controller]}.js") %>
    <%= yield :javascript %>
  </body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Maskstore</title>
    <%= stylesheet_link_tag params[:controller] if ::Rails.application.assets_manifest.find_sources("#{params[:controller]}.css") %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
    <% if content_for?(:head) %>
      <%= yield(:head) %>
    <% end %>
  </head>
  <body class="top-navigation">
    <div id="wrapper" class="<%= params[:controller] %>.<%= params[:action] %>">
      <div id="page-wrapper" class="gray-bg">
        <div class="row border-bottom white-bg">
          <%= render "common/navbar" %>
        </div>
        <%= notice_message %>
        <div class="container">
          <%= yield %>
        </div>
      </div>
      <%= javascript_include_tag params[:controller] if ::Rails.application.assets_manifest.find_sources("#{params[:controller]}.js") %>
      <%= yield :javascript %>
    </div>
  </body>
</html>